#!/bin/sh

dotcloud_get_env() {
    sed -n "/$1/ s/.*: \"\(.*\)\".*/\1/p" < "$HOME/environment.json"
}

setup_django_celery() {
    cat > $HOME/current/supervisord.conf << EOF
[program:djcelery]
directory = $HOME/current/
command = python qrround/manage.py celeryd -E -l info -c 2
stderr_logfile = /var/log/supervisor/%(program_name)s_error.log
stdout_logfile = /var/log/supervisor/%(program_name)s.log

[program:celerycam]
directory = $HOME/current/
command = python qrround/manage.py celerycam
stderr_logfile = /var/log/supervisor/%(program_name)s_error.log
stdout_logfile = /var/log/supervisor/%(program_name)s.log
EOF
}

if [ `dotcloud_get_env SERVICE_NAME` = workers ] ; then
    setup_django_celery

elif [ `dotcloud_get_env SERVICE_NAME` = workers ] ; then
    # python createdb.py
    python qrround/reinstall.py --settings=qrround.settings.dotcloud
    # python mkadmin.py
    mkdir -p /home/dotcloud/data/media /home/dotcloud/volatile/static
    python qrround/manage.py collectstatic --noinput --settings=qrround.settings.dotcloud
    mkdir -p /home/dotcloud/current/qrround/qrround/media/qrcode /home/dotcloud/current/qrround/qrround/media/cache/qrcode
fi
